config/routes.rb
UnknownBusiness::Application.routes.draw do
  
  root 'static_pages#home'
  
  get 'home', to: 'static_pages#home', as: 'home'
  get 'help', to: 'static_pages#help', as: 'help'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'contact', to: 'static_pages#contact', as: 'contact'
  
  resources :subscriptions, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :wallposts, only: [:create, :destroy]
  
  resources :forums do
    resources :subforums, shallow: true
  end
  resources :subforums do
    resources :topics, shallow: true
  end
  resources :topics do
    resources :posts, shallow: true
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  # Session Routes
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  # User Routes
  resources :users, only: [:index, :create] do
    collection do
      get :autocomplete
    end
  end
  get 'verify/:email_auth_token', to: 'users#verify', as: 'verify'
  get 'signup', to: 'users#new', as: 'signup'
  get 'settings', to: 'users#edit'
  get ':username', to: "users#show", as: :user
  patch ':username', to: "users#update"
  delete ':username', to: "users#destroy"
  put ':username', to: "users#admin", as: :admin
  get ':username/following', to: "users#following", as: :following
  get ':username/followers', to: "users#followers", as: :followers
  
  match '*path' => redirect('/'), via: :get

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  # GET /
  def home
    if signed_in? then
      @wallpost = current_user.wallposts.build
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 10)
      @sub_items = current_user.subscription_feed.paginate(page: params[:page], per_page: 10)
    end
  end

  # GET /help
  def help
  end
  
  # GET /about
  def about
  end
  
  # GET /contact
  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% @title = "About"%>

<h1>About</h1>

app/views/static_pages/help.html.erb
<% @title = "Help"%>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% @title = "Ultimate Beta" %>
<% if signed_in? %>
<div class="row">
	<aside class="span4">
		<p>A <b>relationship</b> is the way in which two or more concepts, objects, or people are connected, or the state of being connected.</p>
		<section>
			<%= render 'shared/user_info' %>
			<%= render 'shared/stats' %>
		</section>
		<section>
			<% if signed_in? then %>
			<%= render 'shared/wallpost_form' %>
			<% end %>
		</section>
	</aside>
	<div class="span8">
      <h3>Your Relationships Feed</h3>
      <%= render 'shared/feed' %>
    </div>
    <div class = "span8">
      <h3>Subscription Feed</h3>
      <%= render "shared/subscription_feed" %>
    </div>
</div>
<% else %>
<div class="center hero-unit">
	<h1>Welcome to Ultimate Beta</h1>

	<h2>This is the home page for <%= link_to "Ultimate Beta", help_path %>, which is a start up website geared towards bettering your social experience. </h2>
	<h2>This site is under development and everything is subject to change. If you have any questions, comments, or considerations, <br/> please contact
		<%= mail_to "rszemplinski22@gmail.com" %> or <%= mail_to "ryanklimt@gmail.com" %>. </h2>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>
<% end %>