config/routes.rb
UnknownBusiness::Application.routes.draw do
  
  root 'static_pages#home'
  
  get 'home', to: 'static_pages#home', as: 'home'
  get 'help', to: 'static_pages#help', as: 'help'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'contact', to: 'static_pages#contact', as: 'contact'
  
  resources :subscriptions, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :wallposts, only: [:create, :destroy]
  
  resources :forums do
    resources :subforums, shallow: true
  end
  resources :subforums do
    resources :topics, shallow: true
  end
  resources :topics do
    resources :posts, shallow: true
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  # Session Routes
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  # User Routes
  resources :users, only: [:index, :create] do
    collection do
      get :autocomplete
    end
  end
  get 'verify/:email_auth_token', to: 'users#verify', as: 'verify'
  get 'signup', to: 'users#new', as: 'signup'
  get 'settings', to: 'users#edit'
  get ':username', to: "users#show", as: :user
  patch ':username', to: "users#update"
  delete ':username', to: "users#destroy"
  put ':username', to: "users#admin", as: :admin
  get ':username/following', to: "users#following", as: :following
  get ':username/followers', to: "users#followers", as: :followers
  
  match '*path' => redirect('/'), via: :get

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  
  has_many :subforums, :dependent => :destroy
  
  validates :name, presence: true, length: { maximum: 64 }
  validates :description, presence: true, length: { maximum: 512 }
  
  def most_recent_post
    topic = Topic.first(:order => 'last_post_at DESC', :conditions => ['forum_id = ?', self.id])
    return topic
  end
  
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]
  
  def index
    @forums = Forum.all
  end
  
  def new
    @forum = Forum.new
  end
  
  def create
    @forum = Forum.new(forum_params)
    if @forum.save and current_user.admin? then
      flash[:success] = @forum.name + " forum created!"
      redirect_to @forum
    else
      render 'new'
    end
  end
  
  def show
    @forum = Forum.find(params[:id])
  end
  
  def edit
    @forum = Forum.find(params[:id])
  end
  
  def update
    @forum = Forum.find(params[:id])
    if current_user.admin? and @forum.update_attributes(forum_params) then
      flash[:success] = "Successfully Updated!"
      redirect_to forums_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @forum = Forum.find(params[:id])
    if current_user.admin? then
      @forum.destroy
      flash[:success] = @forum.name + " destroyed!"
      redirect_to forums_path
    else
      redirect_to forums_path
    end
  end
  
  private
  
    def forum_params
      params.require(:forum).permit(:name, :description)
    end
  
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_forum_form.html.erb
<% if @forum.errors.any? %>
    <div class="alert alert-danger"> 
    <p>The form contains <%= pluralize(@forum.errors.count, "error") %>.</p>
    </div>
    <ul>
      <% @forum.errors.full_messages.each do |message| %>
      <li class="text-danger"> <%= message %> </li>
      <% end %>
    </ul>
<% end %>

<div class='form-group'>
	<%= f.label :name, "Name*" %>
	<%= f.text_field :name, class: 'form-control' %>
</div>

<div class='form-group'>
	<%= f.label :description, "Description*" %>
  <%= f.text_area :description, size: "25x6", class: 'form-control' %>
</div>

app/views/forums/edit.html.erb
<% @title = "Edit Forum" %>

<h1>Edit <%= @forum.name %> </h1>

<%= form_for @forum do |t| %>

  <%= render "forum_form", f: t %>

  <%= t.submit "Update Forum", class: "btn btn-primary" %>

<% end %>

app/views/forums/index.html.erb
<% @title = "Forums" %>

<h1>Forums</h1>

<ul>
<% @forums.each do |t| %>
  
  <li><%= link_to t.name, t %>
    <% if signed_in? and current_user.admin? %>
    | <%= link_to 'edit', edit_forum_path(t) %>
    | <%= link_to 'delete', t, method: :delete, data: { confirm: "You sure you want to delete the forum #{t.name}?" } %>
    <% end %>
  </li>
  <span><%= t.description %> </span>
  
<% end %>
</ul>

<% if signed_in? and current_user.admin? %>
  <%= link_to "New Forum", new_forum_path %>
<% end %>

app/views/forums/new.html.erb
<% @title = "New Forum" %>

<h1>New Forum</h1>

<%= form_for @forum do |f| %>

  <%= render "forum_form", f: f %>

  <%= f.submit "Create Forum", class: "btn btn-primary" %>

<% end %>

app/views/forums/show.html.erb
<% @title = @forum.name %>

<h1><%= @forum.name %> </h1>

<span>&laquo;<%= link_to " Back", forums_path %></span>

<ul>
<% for subforum in @forum.subforums %>

  <li>Title: <%= link_to subforum.name, subforum %>
    <% if current_user?(subforum.user) then %>
    	| <%= link_to "edit", edit_subforum_path(subforum) %>
    <% end %>
    <% if (current_user and current_user.admin?) or current_user?(subforum.user) then %>
      | <%= link_to 'delete', subforum, method: :delete, data: { confirm: "You sure you want to delete #{subforum.name}?" } %>
    <% end %>
  </li>
  <span><%= subforum.description %></span>

<% end %>
</ul>

<p><%= link_to "New Sub-Forum", new_forum_subforum_path(@forum.id) %></p>