config/routes.rb
UnknownBusiness::Application.routes.draw do
  
  root 'static_pages#home'
  
  get 'home', to: 'static_pages#home', as: 'home'
  get 'help', to: 'static_pages#help', as: 'help'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'contact', to: 'static_pages#contact', as: 'contact'
  
  resources :subscriptions, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :wallposts, only: [:create, :destroy]
  
  resources :forums do
    resources :subforums, shallow: true
  end
  resources :subforums do
    resources :topics, shallow: true
  end
  resources :topics do
    resources :posts, shallow: true
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  # Session Routes
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  # User Routes
  resources :users, only: [:index, :create] do
    collection do
      get :autocomplete
    end
  end
  get 'verify/:email_auth_token', to: 'users#verify', as: 'verify'
  get 'signup', to: 'users#new', as: 'signup'
  get 'settings', to: 'users#edit'
  get ':username', to: "users#show", as: :user
  patch ':username', to: "users#update"
  delete ':username', to: "users#destroy"
  put ':username', to: "users#admin", as: :admin
  get ':username/following', to: "users#following", as: :following
  get ':username/followers', to: "users#followers", as: :followers
  
  match '*path' => redirect('/'), via: :get

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  
  belongs_to :subforum
  belongs_to :user
  
  has_many :posts, :dependent => :destroy
  
  validates :title, presence: true, length: { maximum: 64 }
  
  default_scope -> { order('created_at DESC') }
  
  accepts_nested_attributes_for :posts, allow_destroy: true
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  before_action :ensure_logged_in, only: [:new, :create, :edit, :update, :destroy]
  
  def new
    sforum = Subforum.find(params[:subforum_id])
    @topic = sforum.topics.build
    post = @topic.posts.build
  end
  
  def create
    sforum = Subforum.find(params[:subforum_id])
    @topic = sforum.topics.build(topic_params)
    @topic.last_poster_id = current_user.id
    @topic.last_post_at = Time.now
    @topic.posts[0].user_id = current_user.id
    if @topic.save then
      flash[:success] = "Topic Created!"
      redirect_to @topic
    else
      render 'new'
    end
  end
  
  def show
    @topic = Topic.find(params[:id])
  end
  
  def destroy
    @topic = Topic.find(params[:id])
    if current_user.admin? or current_user?(@topic.user) then
      @topic.destroy
      flash[:success] = @topic.title + " deleted!"
      redirect_to :back
    else
      flash[:warning] = "You don't have the authority to do that boy!"
      redirect_to root_path
    end
  end
  
  private
  
  def topic_params
    params.require(:topic).permit(:title, :posts_attributes => [:content]).merge(:user_id => current_user.id)
  end
    
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_topic_form.html.erb
<% if @topic.errors.any? %>
    <div class="alert alert-danger"> 
    <p>The form contains <%= pluralize(@topic.errors.count, "error") %>.</p>
    </div>
    <ul>
      <% @topic.errors.full_messages.each do |message| %>
      <li class="text-danger"> <%= message %> </li>
      <% end %>
    </ul>
<% end %>

<div class='form-group'>
	<%= f.label :title, "Title*" %>
	<%= f.text_field :title, class: 'form-control' %>
</div>

<%= f.fields_for :posts do |post| %>
  <div class='form-group'>
	  <%= post.label :content, "Content*" %>
    <%= post.text_area :content, size: "50x6", class: 'form-control' %>
  </div>
<% end %>

app/views/topics/new.html.erb
<% @title = "New Topic" %>

<h1>New Topic</h1>

<%= form_for [@topic.subforum, @topic] do |f| %>

  <%= render "topic_form", f: f %>

  <%= f.submit "Create Topic", class: "btn btn-primary" %>

<% end %>

app/views/topics/show.html.erb
<% @title = @topic.title %>

<h1> <%= @topic.title %> </h1>

<span>&laquo;<%= link_to " Back", subforum_path(@topic.subforum.id) %></span>

<% for post in @topic.posts %>

  <p><%= post.user.username %>: <%= post.content %>
  <% if current_user?(post.user) then %>
    | <%= link_to "edit", edit_post_path(post) %>
  <% end %>
  <% if (signed_in? and current_user.admin?) or current_user?(post.user) then %>
      | <%= link_to "delete", post, method: :delete, data: { confirm: "You sure you want to delete this post?" } %>
  <% end %></p>

<% end %>

<%= link_to "New Post", new_topic_post_path(@topic) %>