config/routes.rb
UnknownBusiness::Application.routes.draw do
  
  root 'static_pages#home'
  
  get 'home', to: 'static_pages#home', as: 'home'
  get 'help', to: 'static_pages#help', as: 'help'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'contact', to: 'static_pages#contact', as: 'contact'
  
  resources :subscriptions, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :wallposts, only: [:create, :destroy]
  
  resources :forums do
    resources :subforums, shallow: true
  end
  resources :subforums do
    resources :topics, shallow: true
  end
  resources :topics do
    resources :posts, shallow: true
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  # Session Routes
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  # User Routes
  resources :users, only: [:index, :create] do
    collection do
      get :autocomplete
    end
  end
  get 'verify/:email_auth_token', to: 'users#verify', as: 'verify'
  get 'signup', to: 'users#new', as: 'signup'
  get 'settings', to: 'users#edit'
  get ':username', to: "users#show", as: :user
  patch ':username', to: "users#update"
  delete ':username', to: "users#destroy"
  put ':username', to: "users#admin", as: :admin
  get ':username/following', to: "users#following", as: :following
  get ':username/followers', to: "users#followers", as: :followers
  
  match '*path' => redirect('/'), via: :get

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger"> 
    <p>The form contains <%= pluralize(object.errors.count, "error") %>.</p>
    </div>
    <ul>
      <% object.errors.full_messages.each do |message| %>
      <li class="text-danger"> <%= message %> </li>
      <% end %>
    </ul>
<% end %>

app/views/shared/_feed.html.erb
<% if !@feed_items.nil? && !@feed_items.empty? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% else %>
	<p>Sorry. Unfortunately you have no relationship feed. <%= link_to "Follow users now!", users_path %></p>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user.username %>
	<span class="timestamp"> <%= link_to feed_item.user.username, user_path(feed_item.user.username) %>
		<%= time_ago_in_words(feed_item.created_at) %> ago </span>
	<span class="content"> <%= feed_item.content %> </span>
	<% if current_user?(feed_item.user) or current_user.admin? %>
		<%= link_to "Delete Post", feed_item, method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, title: feed_item.content %>
	<% end %>
</li>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= "/" + @user.username + "/following" %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= "/" + @user.username + "/followers" %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_subscription_feed.html.erb
<% if !@sub_items.nil? && !@sub_items.empty? %>
  <ol class="subscriptions">
    <% @sub_items.each do |sub| %>
    	<p class = <%= sub.id.to_s %>>
    	<%= link_to sub.subforum.name, sub.subforum %>
    		<% if sub.subforum.topics.any? then %>
	    		<ul>
		    		<% sub.subforum.topics.each do |topic| %>
		    			<li><%= link_to topic.title, topic %></li>
		    		<% end %>
	    		</ul>
    		<% end %>
    	</p>
    <% end %>
  </ol>
  <%= will_paginate @sub_items %>
<% else %>
	<p>Sorry. Unfortunately you have no subscriptions. <%= link_to "Subscribe to one now!", forums_path %></p>
<% end %>

app/views/shared/_subscription_feed_item.html.erb
<li id="<%= sub_item.id %>">
	<span class="content"> <%= link_to sub_item.title, sub_item %> </span>
	<% sub_item.topics.each do |topic| %>
		<p><%= link_to topic.title, topic %></p>
	<% end %>
</li>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), user_path(current_user.username) %>
<h1>
  <%= current_user.username %>
</h1>
<span>
  <%= link_to "view my profile", user_path(current_user.username) %>
</span>
<span>
  <%= pluralize(current_user.wallposts.count, "post") %>
</span>

app/views/shared/_wallpost_form.html.erb
<%= form_for(@wallpost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<% if @user.id == current_user.id then %>
	    <%= f.text_area :content, placeholder: "Share your feelings..." %>
	<% else %>
		<%= f.text_area :content, placeholder: "Post to " + @user.username + "'s profile..." %>
	<% end %>
		<%= f.hidden_field :directed_user_id, value: @user.id %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>